Move phpunit to migrations

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -44,14 +44,12 @@ jobs:
       - name: "Composer install"
         run: composer install --no-interaction --no-progress --dev
 
-      - name: "Run Migration"
+      - name: "Run Migrations and tests"
         run: |
           php bin/console doctrine:database:drop --env=test --force --if-exists || echo "Could not drop database"
-          php bin/console doctrine:database:create --env=test --if-not-exists
+          php bin/console doctrine:database:create --env=test --if-not-exists || echo "Could not create database"
           php bin/console doctrine:migrations:migrate --env=test || echo "No migrations found or migration failed"
-          php bin/console doctrine:fixtures:load --no-interaction || echo "No fixtures found or fixtures failed"
+          php bin/console doctrine:fixtures:load --append --no-interaction || echo "No fixtures found or fixtures failed"
+          php bin/phpunit --coverage-text
         env:
           DATABASE_URL: postgres://app:!ChangeMe!@127.0.0.1:${{ job.services.postgres.ports[5432] }}/app?charset=UTF-8
-
-      - name: "Run tests"
-        run: php bin/phpunit --coverage-text
