Fix workflow migrations

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,7 +11,7 @@ jobs:
 
     services:
       postgres:
-        image: postgres:latest
+        image: postgres:14-alpine
         env:
           POSTGRES_USER: app
           POSTGRES_PASSWORD: '!ChangeMe!'
@@ -46,10 +46,12 @@ jobs:
 
       - name: "Run Migration"
         run: |
-          php bin/console doctrine:schema:update --force || echo "No migrations found or schema update failed"
-          php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
-          php bin/console doctrine:fixtures:load || echo "No fixtures found or fixtures failed"
+          php bin/console doctrine:database:drop --env=test --force --if-exists || echo "Could not drop database"
+          php bin/console doctrine:database:create --env=test --if-not-exists
+          php bin/console doctrine:migrations:migrate --env=test || echo "No migrations found or migration failed"
+          php bin/console doctrine:fixtures:load --no-interaction || echo "No fixtures found or fixtures failed"
         env:
           DATABASE_URL: postgres://app:!ChangeMe!@127.0.0.1:${{ job.services.postgres.ports[5432] }}/app?charset=UTF-8
+
       - name: "Run tests"
-        run: bin/phpunit --coverage-text
+        run: php bin/phpunit --coverage-text
